# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Querykeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busid', models.CharField(max_length=10)),
                ('id_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=12)),
                ('mobile', models.CharField(max_length=15)),
                ('card_number', models.CharField(max_length=30)),
                ('device_id', models.CharField(max_length=50)),
            ],
        ),
    ]
