# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querykeys',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='querykeys',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='querykeys',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='querykeys',
            name='name',
        ),
        migrations.AlterField(
            model_name='querykeys',
            name='id_number',
            field=models.FileField(upload_to='tmpfiles'),
        ),
    ]
