# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20160917_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querykeys',
            name='filepath',
            field=models.FileField(upload_to='F:/Django/xz_up/tmpfiles'),
        ),
    ]
